kind: Deployment
apiVersion: apps/v1
metadata:
  name: todos-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-backend
  template:
    metadata:
      labels:
        app: todos-backend
    spec:
      containers:
        - name: todos-backend
          image: vlukyane/todos:backend_testv1.0.2
          ports:
            - containerPort: 3001
