apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todos-mongo-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-mongo
spec:
  selector:
    matchLabels:
      name: todos-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: todos-mongo
    spec:
      containers:
        - image: mongo
          name: todos-mongo
          volumeMounts:
            - name: todos-mongo-storage
              mountPath: /data/db
      volumes:
        - name: todos-mongo-storage
          persistentVolumeClaim:
            claimName: todos-mongo-claim

