apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todos-web
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: todos-backend-svc
          servicePort: 3001

