kind: Service
apiVersion: v1
metadata:
  name: todos-frontend-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32000
  selector:
    app: todos-frontend-nginx
