apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  containers:
  - image: vlukyane/todos:backendv1
    name: backend
    ports:
    - containerPort: 3001
    resources: {}
  restartPolicy: OnFailure
status: {}
