version: '3'
services:
  backend:
    container_name: backend
    restart: on-failure
    image: vlukyane/todos:backendv1
    ports:
      - '3001:3001'
    depends_on:
      - mongo

  mongo:
    container_name: mongoDB
    restart: on-failure
    image: mongo
    expose:
      - '27017'
    ports:
      - '27017:27017'
networks:
  project_network:
    external: true

