apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongo
spec:
  containers:
  - image: mongo
    name: mongodb
    ports:
    - containerPort: 27017
    resources: {}
  restartPolicy: OnFailure
status: {}
